job:
  title: Historical Pembayaran Listrik

col_identifier: &shared_settings
  non_qr_hist_path: /home/ubuntu/bvic/ibmb_script/pembelian/listrik/historical/data/listrik_historical_data.parquet
  transaction_date: transaction_date
  account_number: from_account_number
  transaction_status: transaction_status
  transaction_state: transaction_state
  transaction_category: transaction_category
  no_referensi: no_referensi
  temp_date_col: temp_date_col
  flag_col: 
    - flag_10min
    - flag_5mio
  usecols:
    - transaction_date
    - from_account_number 
    - from_account_owner_name 
    - to_account_number 
    - to_account_owner_name 
    - to_bank_name 
    - transaction_category 
    - transaction_status 
    - transaction_amount 
    - transaction_currency 
    - channel_code 
    - transaction_state 
    - no_referensi
  n_days: 180
  null_values:
    - "null"
    - "NULL"
    - ""
    - None

dtypes:
  transaction_date: Datetime
  from_account_number: Utf8
  from_account_owner_name: Utf8
  to_account_number: Utf8
  to_account_owner_name: Utf8
  to_bank_name: Utf8
  transaction_category: Utf8
  transaction_status: Int8
  transaction_amount: Float64
  transaction_currency: Utf8
  channel_code: Utf8
  transaction_state: Int8

historical:
  <<: *shared_settings
  input_folder: /home/ubuntu/bvic/data/new_ibmb_data/
  file_prefix: trx_history_
  file_suffix: .csv

update_flag_10min:
  <<: *shared_settings
  daily_path_flag: /home/ubuntu/bvic/ibmb_script/pembelian/listrik/listrik_10min/flagged/listrik_10min_flag.parquet
  flag_col: flag_10min

update_flag_5mio:
  <<: *shared_settings
  daily_path_flag: /home/ubuntu/bvic/ibmb_script/pembelian/listrik/listrik_5mio/flagged/listrik_5mio_flag.parquet
  flag_col: flag_5mio

filter:
  transaction_status:
    - 0
  transaction_state:
    - 1
  transaction_category:
    - PURCHASE_PLN_PREPAIDV2

  
date:
  date_file_format: '%Y%m%d'
  datetime_format: '%Y-%m-%d %H:%M:%S'
